var CONSTANTS = {}

CONSTANTS.NO_ERROR = 0
CONSTANTS.FORMAT_ERROR = 1
CONSTANTS.SERVER_FAILURE = 2
CONSTANTS.NAME_ERROR = 3
CONSTANTS.NOT_IMPLEMENTED = 4
CONSTANTS.REFUSED = 5

CONSTANTS.OPCODES = {
  0 : "QUERY" ,
  1 : "IQUERY",
  2 : "STATUS",
  4 : "NOTIFY",
  5 : "UPDATE",
  "QUERY"  : 0,
  "IQUERY" : 1,
  "STATUS" : 2,
  "NOTIFY" : 4,
  "UPDATE" : 5,
}

CONSTANTS.QUERY  = CONSTANTS.OPCODES["QUERY"]
CONSTANTS.IQUERY = CONSTANTS.OPCODES["IQUERY"]
CONSTANTS.STATUS = CONSTANTS.OPCODES["STATUS"]
CONSTANTS.NOTIFY = CONSTANTS.OPCODES["NOTIFY"]
CONSTANTS.UPDATE = CONSTANTS.OPCODES["UPDATE"]

var opcode = function(o) {
  var r = CONSTANTS.OPCODES[o]
  return r ? r : "unknown"
}

exports.opcode = opcode
